const worldStatus = window.WORLD_STATUS_DATA ?? { acts: [], characters: [], summary: "" };
const sourceCharacters = new Map(worldStatus.characters.map((character) => [character.name, character]));
const sourceActs = new Map(worldStatus.acts.map((act) => [act.act_number, act]));

const characterFromSource = (id, name, role, introducedIn = 0, unlockClue = null) => {
  const source = sourceCharacters.get(name) ?? {};
  return {
    id,
    name,
    role,
    introducedIn,
    unlockClue,
    note: source.description ?? "尚未获得足够信息。",
    status: source.status ?? "",
  };
};

const sceneFromAct = (actNumber, playable) => {
  const act = sourceActs.get(actNumber) ?? {};
  const sourceScenes = act.scenes ?? [];
  const unique = (values) => [...new Set(values.filter(Boolean))];
  return {
    ...playable,
    actNumber,
    eyebrow: `第 ${actNumber} 幕 · ${act.title ?? playable.title}`,
    title: act.title ?? playable.title,
    description: act.dramatic_purpose ?? playable.description,
    briefing: {
      opening: act.opening_state ?? "",
      objective: unique(sourceScenes.map((scene) => scene.objective)).join(" / "),
      conflict: unique(sourceScenes.map((scene) => scene.conflict)).join(" "),
      locations: unique(sourceScenes.map((scene) => scene.location)),
      participants: unique(sourceScenes.flatMap((scene) => scene.participants ?? [])),
      nextHook: act.next_act_hook ?? "",
      sourceClueCount: act.clue_count ?? 0,
    },
  };
};

window.GAME_DATA = {
  summary: worldStatus.summary,
  source: worldStatus.source,
  characters: [
    characterFromSource("gabriel", "Gabriel Conroy", "玩家"),
    characterFromSource("gretta", "Gretta Conroy", "妻子"),
    characterFromSource("lily", "Lily", "女佣"),
    characterFromSource("kate", "Kate Morkan", "姨妈"),
    characterFromSource("julia", "Julia Morkan", "姨妈"),
    characterFromSource("mary", "Mary Jane", "表亲", 1),
    characterFromSource("ivors", "Miss Ivors", "朋友与质问者", 1),
    characterFromSource("freddy", "Freddy Malins", "晚会常客"),
    characterFromSource("browne", "Mr Browne", "晚会常客", 2),
    characterFromSource("darcy", "Bartell D'Arcy", "歌者", 3),
    characterFromSource("michael", "Michael Furey", "记忆中的青年", 4, "michael_name"),
  ],
  scenes: [
    sceneFromAct(1, {
      id: "reception",
      turns: 3,
      actions: [
        {
          id: "observe_lily",
          type: "investigate",
          title: "留意 Lily 的苦涩",
          description: "暂时不解释自己，观察她为何会被一句婚姻玩笑刺痛。",
          outcome: "你意识到她的回答不是一时失礼，而像是长期失望的出口。",
          effects: { empathy: 8, tension: -2 },
          reveals: ["lily_retort"],
        },
        {
          id: "apologize_lily",
          type: "emotion",
          title: "承认自己的冒犯",
          description: "不拿身份和节日气氛掩饰，直接向 Lily 道歉。",
          outcome: "Lily 仍然谨慎，但你的不安第一次没有被硬币和礼貌遮住。",
          effects: { trust: 5, empathy: 6, openness: 5, tension: -4 },
          reveals: ["early_vulnerability"],
        },
        {
          id: "tip_lily",
          type: "emotion",
          title: "用硬币结束尴尬",
          description: "将不安包进节日礼貌里，然后迅速离开。",
          outcome: "Lily 接受了硬币，尴尬被盖住，却没有真正消失。",
          effects: { trust: -2, tension: 6 },
          reveals: ["gabriel_avoidance"],
        },
        {
          id: "inspect_speech_notes",
          type: "investigate",
          title: "检查演讲笔记",
          description: "确认引用和措辞，也留意自己究竟在害怕什么。",
          outcome: "纸上的漂亮句子更像盔甲。你担心听众听不懂，也担心他们看穿你。",
          effects: { openness: 3, tension: 3 },
          reveals: ["speech_notes"],
        },
        {
          id: "check_freddy",
          type: "investigate",
          title: "确认 Freddy 的状态",
          description: "在他失态前判断他需要帮助还是监督。",
          outcome: "Freddy 努力维持体面；晚会的热情也包含替彼此遮掩脆弱。",
          effects: { empathy: 4, trust: 2 },
          reveals: ["freddy_risk"],
        },
      ],
      npc: {
        calm: "Gretta 看见你认真回应 Lily，觉得今晚的你少了一点惯常的防守。",
        tense: "Gretta 注意到你把尴尬匆匆藏好，选择暂时不追问。",
      },
    }),
    sceneFromAct(2, {
      id: "dance",
      turns: 3,
      actions: [
        {
          id: "ask_ivors",
          type: "investigate",
          title: "询问 Miss Ivors 为何在意",
          description: "承认自己不舒服，但请她把质问说完整。",
          outcome: "她的语气仍尖锐，却让你看见身份争论背后的真实重量。",
          effects: { empathy: 6, openness: 8, tension: 3 },
          reveals: ["ivors_conflict", "identity_question"],
        },
        {
          id: "defend_press",
          type: "emotion",
          title: "为 Daily Express 辩护",
          description: "用才华与个人自由回应她的 West Briton 指控。",
          outcome: "你的论点足够漂亮，却使舞步变成了阵地。",
          effects: { tension: 12, openness: -7 },
          reveals: ["daily_express", "ivors_conflict"],
        },
        {
          id: "accept_aran",
          type: "emotion",
          title: "认真考虑 Aran 邀请",
          description: "不把邀请当作政治考试，问她想让你在那里看见什么。",
          outcome: "Miss Ivors 暂时放下讥讽，谈起语言、海岸和一种你不熟悉的归属。",
          effects: { trust: 5, empathy: 7, openness: 9, tension: -2 },
          reveals: ["aran_invitation", "identity_question"],
        },
        {
          id: "watch_gretta_debate",
          type: "investigate",
          title: "观察 Gretta 的反应",
          description: "在反驳前，看一眼来自 Connacht 的妻子如何听这场争论。",
          outcome: "Gretta 没有选边，但你发现自己很少问她如何理解故乡。",
          effects: { empathy: 6, intimacy: 3 },
          reveals: ["gretta_identity"],
        },
        {
          id: "leave_dance",
          type: "emotion",
          title: "结束舞步并退开",
          description: "拒绝继续被质问，把情绪留到演讲中处理。",
          outcome: "冲突停止了，但报复性的句子已经在你的演讲里生根。",
          effects: { tension: 9, openness: -5 },
          reveals: ["gabriel_retreat"],
        },
      ],
      npc: {
        calm: "Miss Ivors 离开前语气缓和了一点，争论没有彻底吞掉你们的友谊。",
        tense: "Miss Ivors 提前离开。你开始在演讲里寻找挽回面子的机会。",
      },
    }),
    sceneFromAct(3, {
      id: "speech",
      turns: 3,
      actions: [
        {
          id: "revise_speech",
          type: "investigate",
          title: "删去报复性的句子",
          description: "重新阅读笔记，辨认哪些话是在赞美主人，哪些话只是针对缺席者。",
          outcome: "演讲少了一次漂亮反击，却更接近你真正想感谢的人。",
          effects: { empathy: 7, openness: 5, tension: -6 },
          reveals: ["generous_speech"],
          requires: ["speech_notes"],
        },
        {
          id: "jab_ivors",
          type: "emotion",
          title: "暗讽新一代",
          description: "借传统与好客之名，回应 Miss Ivors 对你的羞辱。",
          outcome: "宾客鼓掌，但你知道其中一部分热烈来自一场别人没听见的争执。",
          effects: { tension: 11, openness: -7, trust: -3 },
          reveals: ["retaliatory_speech"],
        },
        {
          id: "honor_julia",
          type: "emotion",
          title: "真正赞美 Julia 的歌",
          description: "不把她当作演讲素材，承认歌声使你想到时间与告别。",
          outcome: "Julia 和 Kate 被打动；欢乐第一次容纳了衰老，而不是躲开它。",
          effects: { empathy: 9, trust: 6, intimacy: 3 },
          reveals: ["julia_song", "fragile_hospitality"],
        },
        {
          id: "read_applause",
          type: "investigate",
          title: "观察掌声之后",
          description: "不只接受掌声，留意每个人沉默时的神情。",
          outcome: "演讲获得成功，却没有解决你与任何人的距离。",
          effects: { empathy: 4, openness: 4 },
          reveals: ["applause_distance"],
        },
        {
          id: "carve_and_host",
          type: "emotion",
          title: "专注照料餐桌",
          description: "让鹅肉、酒杯和具体的照顾代替更多宏大句子。",
          outcome: "你在小事中感到自在，也发现好客并不需要被你定义。",
          effects: { trust: 5, tension: -4 },
          reveals: ["hospitality_in_action"],
        },
      ],
      npc: {
        calm: "晚宴在真诚的余韵中结束，Gretta 愿意与你分享离席后的安静。",
        tense: "掌声恢复了你的自信，却没有消除你对被误解的愤怒。",
      },
    }),
    sceneFromAct(4, {
      id: "farewell",
      turns: 3,
      actions: [
        {
          id: "observe_gretta",
          type: "investigate",
          title: "观察楼梯上的 Gretta",
          description: "先不打断她，记住歌声抵达她时的神情。",
          outcome: "她并非只是被旋律感动。那首歌打开了一个你从未进入的房间。",
          effects: { empathy: 7, openness: 4 },
          reveals: ["gretta_reaction"],
        },
        {
          id: "identify_song",
          type: "investigate",
          title: "确认歌曲与歌者",
          description: "询问 Bartell D'Arcy 那段未唱完的旋律。",
          outcome: "你得知它叫《The Lass of Aughrim》，一首关于雨、等待与失去的歌。",
          effects: { empathy: 3 },
          reveals: ["old_song", "darcy_song"],
        },
        {
          id: "ask_about_song",
          type: "emotion",
          title: "问 Gretta 想起了谁",
          description: "直接询问，但不要求她立刻把回忆交出来。",
          outcome: "Gretta 提到一个叫 Michael Furey 的青年，随后又沉默下来。",
          effects: { trust: 5, openness: 7, tension: 3 },
          reveals: ["michael_name"],
          requiresAny: ["gretta_reaction", "old_song", "song_hypothesis"],
        },
        {
          id: "romantic_projection",
          type: "emotion",
          title: "把沉默解释为浪漫",
          description: "沉浸在回酒店后的亲密想象里，不触碰她此刻的悲伤。",
          outcome: "你的期待越来越具体，Gretta 却在马车里离你越来越远。",
          effects: { intimacy: 3, tension: 8, empathy: -4 },
          reveals: ["gretta_distance"],
        },
        {
          id: "carriage_space",
          type: "emotion",
          title: "在马车里留下空间",
          description: "告诉 Gretta，你注意到她难过，但她可以决定何时开口。",
          outcome: "她没有立刻解释，只轻声说那首歌来自她年轻时住过的地方。",
          effects: { trust: 8, intimacy: 5, empathy: 7, tension: -5 },
          reveals: ["galway_memory"],
        },
      ],
      npc: {
        calm: "抵达酒店时，Gretta 知道你会听见一个不属于你的故事。",
        tense: "抵达酒店时，你们都感到房间里即将发生一场对峙。",
      },
    }),
    sceneFromAct(5, {
      id: "revelation",
      turns: 3,
      actions: [
        {
          id: "ask_michael_gently",
          type: "emotion",
          title: "温和地询问 Michael",
          description: "告诉她，你想理解，而不是审判。",
          outcome: "Gretta 讲起那个在雨中来到窗下、随后死去的青年。",
          effects: { trust: 12, openness: 14, empathy: 9, tension: -5 },
          reveals: ["rain_visit", "michael_truth"],
          requiresAny: ["michael_name", "song_hypothesis", "galway_memory"],
        },
        {
          id: "share_insecurity",
          type: "emotion",
          title: "承认自己的嫉妒与局限",
          description: "不把不安变成指控，承认自己从未真正了解她。",
          outcome: "Gretta 没有立即安慰你，但她不再需要防御你的愤怒。",
          effects: { trust: 9, intimacy: 8, openness: 7, tension: -4, empathy: 4 },
          reveals: ["gabriel_vulnerability"],
          requiresAny: ["michael_name", "self_hypothesis", "gretta_distance"],
        },
        {
          id: "offer_silence",
          type: "emotion",
          title: "允许她安静地悲伤",
          description: "不要求答案，只在她身边留下空间。",
          outcome: "沉默没有解决一切，却使悲伤不再需要辩护。",
          effects: { trust: 8, intimacy: 5, empathy: 12, tension: -8 },
          reveals: ["compassionate_silence"],
        },
        {
          id: "compare_love",
          type: "emotion",
          title: "追问她是否更爱 Michael",
          description: "要求过去与现在给出一个明确胜负。",
          outcome: "Gretta 的悲伤被迫变成辩护。你得到答案碎片，却失去靠近它的方式。",
          effects: { trust: -15, intimacy: -10, tension: 22, openness: -12 },
          reveals: ["jealous_wound"],
          requires: ["michael_name"],
        },
        {
          id: "look_at_snow",
          type: "investigate",
          title: "凝视窗外的雪",
          description: "把今晚的人与远方的死者放在同一场雪中思考。",
          outcome: "你的身份短暂松动，理解不再意味着占有。",
          effects: { empathy: 15, tension: -5, openness: 6 },
          reveals: ["snow_reflection"],
        },
      ],
      npc: {
        calm: "Gretta 睡去后，你终于不再把她的过去视为对自己的判决。",
        tense: "Gretta 转身睡去。你仍在试图让那个死者与你分出胜负。",
      },
    }),
  ],
  clues: {
    lily_retort: { title: "Lily 的苦涩回答", kind: "testimony", character: "lily", text: "一句婚姻玩笑踩中了她长期承受的失望。" },
    early_vulnerability: { title: "一次不带借口的道歉", kind: "confirmed", character: "gabriel", text: "Gabriel 可以承认失言，而不必立刻恢复体面。" },
    gabriel_avoidance: { title: "用礼貌逃离尴尬", kind: "observation", character: "gabriel", text: "Gabriel 常用礼貌动作避免面对失败的交流。" },
    speech_notes: { title: "演讲笔记", kind: "observation", character: "gabriel", text: "精心准备的引用既是工具，也是对被误解的防御。" },
    freddy_risk: { title: "Freddy 的勉强体面", kind: "observation", character: "freddy", text: "晚会的热情也包含替常客遮掩脆弱。" },
    ivors_conflict: { title: "West Briton 的指控", kind: "testimony", character: "ivors", text: "Miss Ivors 认为 Gabriel 的文化选择带有政治意义。" },
    identity_question: { title: "身份并非抽象问题", kind: "confirmed", character: "ivors", text: "文化与归属会真实影响人与人的距离。" },
    daily_express: { title: "Daily Express 的文学评论", kind: "confirmed", character: "gabriel", text: "Gabriel 的写作工作被部分朋友视为亲英立场。" },
    aran_invitation: { title: "Aran Isles 的邀请", kind: "testimony", character: "ivors", text: "邀请既是旅行提议，也是一次归属感的挑战。" },
    gretta_identity: { title: "来自 Connacht 的 Gretta", kind: "observation", character: "gretta", text: "Gabriel 很少询问妻子如何理解自己的故乡。" },
    gabriel_retreat: { title: "退回演讲的争执", kind: "observation", character: "gabriel", text: "无法完成的对话会被 Gabriel 带进另一个场合。" },
    generous_speech: { title: "删去报复的演讲", kind: "confirmed", character: "gabriel", text: "感谢不需要通过贬低缺席者来成立。" },
    retaliatory_speech: { title: "掌声中的暗讽", kind: "confirmed", character: "gabriel", text: "公开成功也可能掩盖私人报复。" },
    julia_song: { title: "Julia 歌声中的衰老", kind: "observation", character: "julia", text: "欢乐之中已经存在失去与告别。" },
    fragile_hospitality: { title: "好客容纳脆弱", kind: "confirmed", character: "kate", text: "晚会的温暖来自彼此照料，而不只是传统辞藻。" },
    applause_distance: { title: "掌声之后的距离", kind: "observation", character: "gabriel", text: "演讲成功没有自动解决任何一段关系。" },
    hospitality_in_action: { title: "餐桌上的具体照料", kind: "confirmed", character: "kate", text: "好客也存在于分餐、添酒和留意他人的小动作里。" },
    gretta_reaction: { title: "Gretta 在楼梯上的神情", kind: "observation", character: "gretta", text: "歌声触发了强烈且私密的记忆。" },
    old_song: { title: "《The Lass of Aughrim》", kind: "confirmed", character: "gretta", text: "一首关于雨、等待与失去的旧歌。" },
    darcy_song: { title: "Bartell D'Arcy 未唱完的歌", kind: "observation", character: "darcy", text: "一段偶然歌声改变了晚会之后的一切。" },
    michael_name: { title: "Michael Furey", kind: "testimony", character: "michael", text: "Gretta 年轻时认识、至今仍会为之悲伤的人。" },
    gretta_distance: { title: "马车中的两种心境", kind: "observation", character: "gretta", text: "Gabriel 的浪漫期待与 Gretta 的悲伤并不同步。" },
    galway_memory: { title: "来自 Galway 的回忆", kind: "testimony", character: "gretta", text: "歌曲与 Gretta 年轻时居住的地方相连。" },
    rain_visit: { title: "雨中的最后探望", kind: "testimony", character: "michael", text: "Michael 在病中来到 Gretta 窗下，随后去世。" },
    michael_truth: { title: "Michael 的死亡", kind: "confirmed", character: "michael", text: "他的死亡与对 Gretta 的情感紧密相连。" },
    gabriel_vulnerability: { title: "Gabriel 承认不安", kind: "confirmed", character: "gabriel", text: "脆弱可以成为交流，而不必成为攻击。" },
    compassionate_silence: { title: "不要求解释的陪伴", kind: "confirmed", character: "gretta", text: "陪伴有时比立即获得答案更重要。" },
    jealous_wound: { title: "被迫比较的爱情", kind: "confirmed", character: "gretta", text: "将爱变成胜负会伤害当下关系。" },
    snow_reflection: { title: "落在所有人身上的雪", kind: "observation", character: "gabriel", text: "活人与死者、熟悉与陌生被同一场雪连接。" },
  },
  hypotheses: [
    {
      id: "self_hypothesis",
      title: "Gabriel 的防守模式",
      character: "gabriel",
      requiresAnyPairs: [["lily_retort", "ivors_conflict"], ["gabriel_avoidance", "ivors_conflict"]],
      text: "当交流失控时，Gabriel 会用礼貌、知识或反驳保护自己。",
      effects: { empathy: 5, tension: -3 },
    },
    {
      id: "identity_hypothesis",
      title: "旅行也是一种立场",
      character: "ivors",
      requires: ["daily_express", "aran_invitation"],
      text: "Miss Ivors 质问的不是行程，而是 Gabriel 愿意把哪里视为值得理解的世界。",
      effects: { empathy: 6, openness: 4 },
    },
    {
      id: "speech_hypothesis",
      title: "演讲无法替代交谈",
      character: "gabriel",
      requiresAnyPairs: [["speech_notes", "applause_distance"], ["retaliatory_speech", "applause_distance"]],
      text: "公开表达可以成功，却仍然回避具体关系中的不安。",
      effects: { empathy: 5, openness: 4 },
    },
    {
      id: "song_hypothesis",
      title: "歌曲通往 Gretta 隐藏的过去",
      character: "gretta",
      requires: ["gretta_reaction", "old_song"],
      text: "她的悲伤并非关于宴会，而是关于歌声唤醒的人。",
      effects: { empathy: 5, openness: 3 },
    },
    {
      id: "memory_hypothesis",
      title: "Galway 与 Michael 相连",
      character: "michael",
      requires: ["galway_memory", "michael_name"],
      text: "那个人并非抽象的旧情，而属于 Gretta 在 Galway 的完整人生。",
      effects: { empathy: 6, tension: -2 },
    },
    {
      id: "love_hypothesis",
      title: "理解不等于占有",
      character: "gabriel",
      requires: ["michael_truth", "snow_reflection"],
      text: "理解 Gretta 的过去，不需要 Gabriel 在过去中获胜。",
      effects: { empathy: 8, trust: 4 },
    },
  ],
};
